export const GET_ERRORS = 'GET_ERRORS';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';