export const GET_ERRORS = 'GET_ERRORS';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';

export const GET_MENUS = 'GET_MENUS';
export const GET_MENU = 'GET_MENU';
export const DELETE_MENU = 'DELETE_MENU';
export const CREATE_MENU = 'CREATE_MENU';

export const GET_MENU_ITEMS = 'GET_MENU_ITEMS';
export const GET_MENU_ITEM = 'GET_MENU_ITEM';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const CREATE_MENU_ITEM = 'CREATE_MENU_ITEM';